// Code generated by "stringer -type=LayerIndex"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BASE-0]
	_ = x[MAXLAYERINDEX-1]
}

const _LayerIndex_name = "BASEMAXLAYERINDEX"

var _LayerIndex_index = [...]uint8{0, 4, 17}

func (i LayerIndex) String() string {
	if i < 0 || i >= LayerIndex(len(_LayerIndex_index)-1) {
		return "LayerIndex(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LayerIndex_name[_LayerIndex_index[i]:_LayerIndex_index[i+1]]
}
