package main

import "testing"
import "github.com/stretchr/testify/assert"

func TestRowColSerial(t *testing.T) {
	assert.Equal(t, 1, l(1, 1).Serial())
	assert.Equal(t, 2, l(1, 2).Serial())
	assert.Equal(t, 3, l(1, 3).Serial())
	assert.Equal(t, 4, l(1, 4).Serial())
	assert.Equal(t, 5, l(1, 5).Serial())
	assert.Equal(t, 6, l(1, 6).Serial())
	assert.Equal(t, 7, r(1, 1).Serial())
	assert.Equal(t, 8, r(1, 2).Serial())
	assert.Equal(t, 9, r(1, 3).Serial())
	assert.Equal(t, 10, r(1, 4).Serial())
	assert.Equal(t, 11, r(1, 5).Serial())
	assert.Equal(t, 12, r(1, 6).Serial())
	assert.Equal(t, 13, l(2, 1).Serial())
	assert.Equal(t, 14, l(2, 2).Serial())
	assert.Equal(t, 15, l(2, 3).Serial())
	assert.Equal(t, 16, l(2, 4).Serial())
	assert.Equal(t, 17, l(2, 5).Serial())
	assert.Equal(t, 18, l(2, 6).Serial())
	assert.Equal(t, 19, r(2, 1).Serial())
	assert.Equal(t, 20, r(2, 2).Serial())
	assert.Equal(t, 21, r(2, 3).Serial())
	assert.Equal(t, 22, r(2, 4).Serial())
	assert.Equal(t, 23, r(2, 5).Serial())
	assert.Equal(t, 24, r(2, 6).Serial())
	assert.Equal(t, 25, l(3, 1).Serial())
	assert.Equal(t, 26, l(3, 2).Serial())
	assert.Equal(t, 27, l(3, 3).Serial())
	assert.Equal(t, 28, l(3, 4).Serial())
	assert.Equal(t, 29, l(3, 5).Serial())
	assert.Equal(t, 30, l(3, 6).Serial())
	assert.Equal(t, 31, r(3, 1).Serial())
	assert.Equal(t, 32, r(3, 2).Serial())
	assert.Equal(t, 33, r(3, 3).Serial())
	assert.Equal(t, 34, r(3, 4).Serial())
	assert.Equal(t, 35, r(3, 5).Serial())
	assert.Equal(t, 36, r(3, 6).Serial())
	assert.Equal(t, 37, l(4, 1).Serial())
	assert.Equal(t, 38, l(4, 2).Serial())
	assert.Equal(t, 39, l(4, 3).Serial())
	assert.Equal(t, 40, r(4, 1).Serial())
	assert.Equal(t, 41, r(4, 2).Serial())
	assert.Equal(t, 42, r(4, 3).Serial())
}
