// Code generated by "stringer -type=LayerIndex"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ComboAllLayers - -1]
	_ = x[BASE-0]
	_ = x[MOVE-1]
	_ = x[NUM-2]
	_ = x[QUICK-3]
	_ = x[REPEAT-4]
	_ = x[SYS-5]
	_ = x[PARENS-6]
	_ = x[CHAINS-7]
	_ = x[MAXLAYERINDEX-8]
}

const _LayerIndex_name = "ComboAllLayersBASEMOVENUMQUICKREPEATSYSPARENSCHAINSMAXLAYERINDEX"

var _LayerIndex_index = [...]uint8{0, 14, 18, 22, 25, 30, 36, 39, 45, 51, 64}

func (i LayerIndex) String() string {
	i -= -1
	if i < 0 || i >= LayerIndex(len(_LayerIndex_index)-1) {
		return "LayerIndex(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _LayerIndex_name[_LayerIndex_index[i]:_LayerIndex_index[i+1]]
}
