package key

import (
	"fmt"
	"strconv"

	"keyboard/util"
)

var LA = modBuilder("LA")
var LC = modBuilder("LC")
var LG = modBuilder("LG")
var LS = modBuilder("LS")
var RA = modBuilder("RA")
var RG = modBuilder("RG")
var RS = modBuilder("RS")
var RC = modBuilder("RC")

func From(b byte) Key {
	switch {
	case b >= 'A' && b <= 'Z':
		return LS(Key(b))
	case b >= 'a' && b <= 'z':
		// keys constants are upper case
		return Key(b - 'a' + 'A')
	case b >= '0' && b <= '9':
		return Key('N' + b)
	}

	k, ok := map[byte]Key{
		' ':  SPACE,
		'-':  MINUS,
		'+':  PLUS,
		'=':  EQUAL,
		'[':  LBKT,
		']':  RBKT,
		'{':  LBRC,
		'}':  RBRC,
		'(':  LPAR,
		')':  RPAR,
		'<':  LT,
		'>':  GT,
		'/':  SLASH,
		'\\': BSLH,
		':':  COLON,
		';':  SEMI,
		',':  COMMA,
		'.':  DOT,
		'"':  DQT,
		'`':  GRAVE,
		'\'': SQT,
		'?':  QMARK,
		'$':  DOLLAR,
		'\t': TAB,
		'\n': RETURN,
		'\a': ESC,
		'\b': LEFT,
		'!':  EXCL,
		'#':  HASH,
		'%':  PRCNT,
		'&':  AMPS,
		'*':  STAR,
		'@':  AT,
		'^':  CARET,
		'_':  UNDER,
		'|':  PIPE,
		'~':  TILDE,
	}[b]

	util.Panicif(!ok, "unhandled byte: %c (%d)", b, b)

	return k
}

func modBuilder(name string) func(Key) Key {
	return func(k Key) Key {
		return Key(fmt.Sprintf("%s(%s)", name, k))
	}
}

type Number int

func (n Number) String() string {
	return strconv.Itoa(int(n))
}

var ZERO = Number(0)

const (
	MACRO_PLACEHOLDER                      Key = "MACRO_PLACEHOLDER"
	MCLK                                   Key = "MCLK"
	LCLK                                   Key = "LCLK"
	RCLK                                   Key = "RCLK"
	SYSTEM_POWER                           Key = "SYSTEM_POWER"
	SYS_PWR                                Key = "SYS_PWR"
	SYSTEM_SLEEP                           Key = "SYSTEM_SLEEP"
	SYS_SLEEP                              Key = "SYS_SLEEP"
	SYSTEM_WAKE_UP                         Key = "SYSTEM_WAKE_UP"
	SYS_WAKE                               Key = "SYS_WAKE"
	A                                      Key = "A"
	B                                      Key = "B"
	C                                      Key = "C"
	D                                      Key = "D"
	E                                      Key = "E"
	F                                      Key = "F"
	G                                      Key = "G"
	H                                      Key = "H"
	I                                      Key = "I"
	J                                      Key = "J"
	K                                      Key = "K"
	L                                      Key = "L"
	M                                      Key = "M"
	N                                      Key = "N"
	O                                      Key = "O"
	P                                      Key = "P"
	Q                                      Key = "Q"
	R                                      Key = "R"
	S                                      Key = "S"
	T                                      Key = "T"
	U                                      Key = "U"
	V                                      Key = "V"
	W                                      Key = "W"
	X                                      Key = "X"
	Y                                      Key = "Y"
	Z                                      Key = "Z"
	NUMBER_1                               Key = "NUMBER_1"
	N1                                     Key = "N1"
	EXCLAMATION                            Key = "EXCLAMATION"
	EXCL                                   Key = "EXCL"
	NUMBER_2                               Key = "NUMBER_2"
	N2                                     Key = "N2"
	AT_SIGN                                Key = "AT_SIGN"
	AT                                     Key = "AT"
	NUMBER_3                               Key = "NUMBER_3"
	N3                                     Key = "N3"
	HASH                                   Key = "HASH"
	POUND                                  Key = "POUND"
	NUMBER_4                               Key = "NUMBER_4"
	N4                                     Key = "N4"
	DOLLAR                                 Key = "DOLLAR"
	DLLR                                   Key = "DLLR"
	NUMBER_5                               Key = "NUMBER_5"
	N5                                     Key = "N5"
	PERCENT                                Key = "PERCENT"
	PRCNT                                  Key = "PRCNT"
	NUMBER_6                               Key = "NUMBER_6"
	N6                                     Key = "N6"
	CARET                                  Key = "CARET"
	NUMBER_7                               Key = "NUMBER_7"
	N7                                     Key = "N7"
	AMPERSAND                              Key = "AMPERSAND"
	AMPS                                   Key = "AMPS"
	NUMBER_8                               Key = "NUMBER_8"
	N8                                     Key = "N8"
	ASTERISK                               Key = "ASTERISK"
	ASTRK                                  Key = "ASTRK"
	STAR                                   Key = "STAR"
	NUMBER_9                               Key = "NUMBER_9"
	N9                                     Key = "N9"
	LEFT_PARENTHESIS                       Key = "LEFT_PARENTHESIS"
	LPAR                                   Key = "LPAR"
	NUMBER_0                               Key = "NUMBER_0"
	N0                                     Key = "N0"
	RIGHT_PARENTHESIS                      Key = "RIGHT_PARENTHESIS"
	RPAR                                   Key = "RPAR"
	RETURN                                 Key = "RETURN"
	ENTER                                  Key = "ENTER"
	RET                                    Key = "RET"
	ESCAPE                                 Key = "ESCAPE"
	ESC                                    Key = "ESC"
	BACKSPACE                              Key = "BACKSPACE"
	BSPC                                   Key = "BSPC"
	TAB                                    Key = "TAB"
	SPACE                                  Key = "SPACE"
	MINUS                                  Key = "MINUS"
	UNDERSCORE                             Key = "UNDERSCORE"
	UNDER                                  Key = "UNDER"
	EQUAL                                  Key = "EQUAL"
	PLUS                                   Key = "PLUS"
	LEFT_BRACKET                           Key = "LEFT_BRACKET"
	LBKT                                   Key = "LBKT"
	LEFT_BRACE                             Key = "LEFT_BRACE"
	LBRC                                   Key = "LBRC"
	RIGHT_BRACKET                          Key = "RIGHT_BRACKET"
	RBKT                                   Key = "RBKT"
	RIGHT_BRACE                            Key = "RIGHT_BRACE"
	RBRC                                   Key = "RBRC"
	BACKSLASH                              Key = "BACKSLASH"
	BSLH                                   Key = "BSLH"
	PIPE                                   Key = "PIPE"
	NON_US_HASH                            Key = "NON_US_HASH"
	NUHS                                   Key = "NUHS"
	TILDE2                                 Key = "TILDE2"
	SEMICOLON                              Key = "SEMICOLON"
	SEMI                                   Key = "SEMI"
	COLON                                  Key = "COLON"
	SINGLE_QUOTE                           Key = "SINGLE_QUOTE"
	SQT                                    Key = "SQT"
	APOSTROPHE                             Key = "APOSTROPHE"
	APOS                                   Key = "APOS"
	DOUBLE_QUOTES                          Key = "DOUBLE_QUOTES"
	DQT                                    Key = "DQT"
	GRAVE                                  Key = "GRAVE"
	TILDE                                  Key = "TILDE"
	COMMA                                  Key = "COMMA"
	LESS_THAN                              Key = "LESS_THAN"
	LT                                     Key = "LT"
	PERIOD                                 Key = "PERIOD"
	DOT                                    Key = "DOT"
	GREATER_THAN                           Key = "GREATER_THAN"
	GT                                     Key = "GT"
	SLASH                                  Key = "SLASH"
	FSLH                                   Key = "FSLH"
	QUESTION                               Key = "QUESTION"
	QMARK                                  Key = "QMARK"
	CAPSLOCK                               Key = "CAPSLOCK"
	CAPS                                   Key = "CAPS"
	CLCK                                   Key = "CLCK"
	F1                                     Key = "F1"
	F2                                     Key = "F2"
	F3                                     Key = "F3"
	F4                                     Key = "F4"
	F5                                     Key = "F5"
	F6                                     Key = "F6"
	F7                                     Key = "F7"
	F8                                     Key = "F8"
	F9                                     Key = "F9"
	F10                                    Key = "F10"
	F11                                    Key = "F11"
	F12                                    Key = "F12"
	PRINTSCREEN                            Key = "PRINTSCREEN"
	PSCRN                                  Key = "PSCRN"
	SCROLLLOCK                             Key = "SCROLLLOCK"
	SLCK                                   Key = "SLCK"
	PAUSE_BREAK                            Key = "PAUSE_BREAK"
	INSERT                                 Key = "INSERT"
	INS                                    Key = "INS"
	HOME                                   Key = "HOME"
	PAGE_UP                                Key = "PAGE_UP"
	PG_UP                                  Key = "PG_UP"
	DELETE                                 Key = "DELETE"
	DEL                                    Key = "DEL"
	END                                    Key = "END"
	PAGE_DOWN                              Key = "PAGE_DOWN"
	PG_DN                                  Key = "PG_DN"
	RIGHT_ARROW                            Key = "RIGHT_ARROW"
	RIGHT                                  Key = "RIGHT"
	LEFT_ARROW                             Key = "LEFT_ARROW"
	LEFT                                   Key = "LEFT"
	DOWN_ARROW                             Key = "DOWN_ARROW"
	DOWN                                   Key = "DOWN"
	UP_ARROW                               Key = "UP_ARROW"
	UP                                     Key = "UP"
	KP_NUMLOCK                             Key = "KP_NUMLOCK"
	KP_NUM                                 Key = "KP_NUM"
	KP_NLCK                                Key = "KP_NLCK"
	CLEAR2                                 Key = "CLEAR2"
	KP_DIVIDE                              Key = "KP_DIVIDE"
	KP_SLASH                               Key = "KP_SLASH"
	KP_MULTIPLY                            Key = "KP_MULTIPLY"
	KP_ASTERISK                            Key = "KP_ASTERISK"
	KP_MINUS                               Key = "KP_MINUS"
	KP_SUBTRACT                            Key = "KP_SUBTRACT"
	KP_PLUS                                Key = "KP_PLUS"
	KP_ENTER                               Key = "KP_ENTER"
	KP_NUMBER_1                            Key = "KP_NUMBER_1"
	KP_N1                                  Key = "KP_N1"
	KP_NUMBER_2                            Key = "KP_NUMBER_2"
	KP_N2                                  Key = "KP_N2"
	KP_NUMBER_3                            Key = "KP_NUMBER_3"
	KP_N3                                  Key = "KP_N3"
	KP_NUMBER_4                            Key = "KP_NUMBER_4"
	KP_N4                                  Key = "KP_N4"
	KP_NUMBER_5                            Key = "KP_NUMBER_5"
	KP_N5                                  Key = "KP_N5"
	KP_NUMBER_6                            Key = "KP_NUMBER_6"
	KP_N6                                  Key = "KP_N6"
	KP_NUMBER_7                            Key = "KP_NUMBER_7"
	KP_N7                                  Key = "KP_N7"
	KP_NUMBER_8                            Key = "KP_NUMBER_8"
	KP_N8                                  Key = "KP_N8"
	KP_NUMBER_9                            Key = "KP_NUMBER_9"
	KP_N9                                  Key = "KP_N9"
	KP_NUMBER_0                            Key = "KP_NUMBER_0"
	KP_N0                                  Key = "KP_N0"
	KP_DOT                                 Key = "KP_DOT"
	NON_US_BACKSLASH                       Key = "NON_US_BACKSLASH"
	NON_US_BSLH                            Key = "NON_US_BSLH"
	NUBS                                   Key = "NUBS"
	PIPE2                                  Key = "PIPE2"
	K_APPLICATION                          Key = "K_APPLICATION"
	K_APP                                  Key = "K_APP"
	K_CONTEXT_MENU                         Key = "K_CONTEXT_MENU"
	K_CMENU                                Key = "K_CMENU"
	K_POWER                                Key = "K_POWER"
	K_PWR                                  Key = "K_PWR"
	KP_EQUAL                               Key = "KP_EQUAL"
	F13                                    Key = "F13"
	F14                                    Key = "F14"
	F15                                    Key = "F15"
	F16                                    Key = "F16"
	F17                                    Key = "F17"
	F18                                    Key = "F18"
	F19                                    Key = "F19"
	F20                                    Key = "F20"
	F21                                    Key = "F21"
	F22                                    Key = "F22"
	F23                                    Key = "F23"
	F24                                    Key = "F24"
	K_EXECUTE                              Key = "K_EXECUTE"
	K_EXEC                                 Key = "K_EXEC"
	K_HELP                                 Key = "K_HELP"
	K_MENU                                 Key = "K_MENU"
	K_SELECT                               Key = "K_SELECT"
	K_STOP                                 Key = "K_STOP"
	K_AGAIN                                Key = "K_AGAIN"
	K_REDO                                 Key = "K_REDO"
	K_UNDO                                 Key = "K_UNDO"
	K_CUT                                  Key = "K_CUT"
	K_COPY                                 Key = "K_COPY"
	K_PASTE                                Key = "K_PASTE"
	K_FIND                                 Key = "K_FIND"
	K_MUTE                                 Key = "K_MUTE"
	K_VOLUME_UP                            Key = "K_VOLUME_UP"
	K_VOL_UP                               Key = "K_VOL_UP"
	K_VOLUME_DOWN                          Key = "K_VOLUME_DOWN"
	K_VOL_DN                               Key = "K_VOL_DN"
	LOCKING_CAPS                           Key = "LOCKING_CAPS"
	LCAPS                                  Key = "LCAPS"
	LOCKING_NUM                            Key = "LOCKING_NUM"
	LNLCK                                  Key = "LNLCK"
	LOCKING_SCROLL                         Key = "LOCKING_SCROLL"
	LSLCK                                  Key = "LSLCK"
	KP_COMMA                               Key = "KP_COMMA"
	KP_EQUAL_AS400                         Key = "KP_EQUAL_AS400"
	INTERNATIONAL_1                        Key = "INTERNATIONAL_1"
	INT1                                   Key = "INT1"
	INT_RO                                 Key = "INT_RO"
	INTERNATIONAL_2                        Key = "INTERNATIONAL_2"
	INT2                                   Key = "INT2"
	INT_KATAKANAHIRAGANA                   Key = "INT_KATAKANAHIRAGANA"
	INT_KANA                               Key = "INT_KANA"
	INTERNATIONAL_3                        Key = "INTERNATIONAL_3"
	INT3                                   Key = "INT3"
	INT_YEN                                Key = "INT_YEN"
	INTERNATIONAL_4                        Key = "INTERNATIONAL_4"
	INT4                                   Key = "INT4"
	INT_HENKAN                             Key = "INT_HENKAN"
	INTERNATIONAL_5                        Key = "INTERNATIONAL_5"
	INT5                                   Key = "INT5"
	INT_MUHENKAN                           Key = "INT_MUHENKAN"
	INTERNATIONAL_6                        Key = "INTERNATIONAL_6"
	INT6                                   Key = "INT6"
	INT_KPJPCOMMA                          Key = "INT_KPJPCOMMA"
	INTERNATIONAL_7                        Key = "INTERNATIONAL_7"
	INT7                                   Key = "INT7"
	INTERNATIONAL_8                        Key = "INTERNATIONAL_8"
	INT8                                   Key = "INT8"
	INTERNATIONAL_9                        Key = "INTERNATIONAL_9"
	INT9                                   Key = "INT9"
	LANGUAGE_1                             Key = "LANGUAGE_1"
	LANG1                                  Key = "LANG1"
	LANG_HANGEUL                           Key = "LANG_HANGEUL"
	LANGUAGE_2                             Key = "LANGUAGE_2"
	LANG2                                  Key = "LANG2"
	LANG_HANJA                             Key = "LANG_HANJA"
	LANGUAGE_3                             Key = "LANGUAGE_3"
	LANG3                                  Key = "LANG3"
	LANG_KATAKANA                          Key = "LANG_KATAKANA"
	LANGUAGE_4                             Key = "LANGUAGE_4"
	LANG4                                  Key = "LANG4"
	LANG_HIRAGANA                          Key = "LANG_HIRAGANA"
	LANGUAGE_5                             Key = "LANGUAGE_5"
	LANG5                                  Key = "LANG5"
	LANG_ZENKAKUHANKAKU                    Key = "LANG_ZENKAKUHANKAKU"
	LANGUAGE_6                             Key = "LANGUAGE_6"
	LANG6                                  Key = "LANG6"
	LANGUAGE_7                             Key = "LANGUAGE_7"
	LANG7                                  Key = "LANG7"
	LANGUAGE_8                             Key = "LANGUAGE_8"
	LANG8                                  Key = "LANG8"
	LANGUAGE_9                             Key = "LANGUAGE_9"
	LANG9                                  Key = "LANG9"
	ALT_ERASE                              Key = "ALT_ERASE"
	SYSREQ                                 Key = "SYSREQ"
	ATTENTION                              Key = "ATTENTION"
	K_CANCEL                               Key = "K_CANCEL"
	CLEAR                                  Key = "CLEAR"
	PRIOR                                  Key = "PRIOR"
	RETURN2                                Key = "RETURN2"
	RET2                                   Key = "RET2"
	SEPARATOR                              Key = "SEPARATOR"
	OUT                                    Key = "OUT"
	OPER                                   Key = "OPER"
	CLEAR_AGAIN                            Key = "CLEAR_AGAIN"
	CRSEL                                  Key = "CRSEL"
	EXSEL                                  Key = "EXSEL"
	CURU                                   Key = "CURU"
	KP_LEFT_PARENTHESIS                    Key = "KP_LEFT_PARENTHESIS"
	KP_LPAR                                Key = "KP_LPAR"
	KP_RIGHT_PARENTHESIS                   Key = "KP_RIGHT_PARENTHESIS"
	KP_RPAR                                Key = "KP_RPAR"
	KSPC                                   Key = "KSPC"
	KP_CLEAR                               Key = "KP_CLEAR"
	LEFT_CONTROL                           Key = "LEFT_CONTROL"
	LCTRL                                  Key = "LCTRL"
	LEFT_SHIFT                             Key = "LEFT_SHIFT"
	LSHIFT                                 Key = "LSHIFT"
	LSHFT                                  Key = "LSHFT"
	LEFT_ALT                               Key = "LEFT_ALT"
	LALT                                   Key = "LALT"
	LEFT_GUI                               Key = "LEFT_GUI"
	LGUI                                   Key = "LGUI"
	LEFT_WIN                               Key = "LEFT_WIN"
	LWIN                                   Key = "LWIN"
	LEFT_COMMAND                           Key = "LEFT_COMMAND"
	LCMD                                   Key = "LCMD"
	LEFT_META                              Key = "LEFT_META"
	LMETA                                  Key = "LMETA"
	RIGHT_CONTROL                          Key = "RIGHT_CONTROL"
	RCTRL                                  Key = "RCTRL"
	RIGHT_SHIFT                            Key = "RIGHT_SHIFT"
	RSHIFT                                 Key = "RSHIFT"
	RSHFT                                  Key = "RSHFT"
	RIGHT_ALT                              Key = "RIGHT_ALT"
	RALT                                   Key = "RALT"
	RIGHT_GUI                              Key = "RIGHT_GUI"
	RGUI                                   Key = "RGUI"
	RIGHT_WIN                              Key = "RIGHT_WIN"
	RWIN                                   Key = "RWIN"
	RIGHT_COMMAND                          Key = "RIGHT_COMMAND"
	RCMD                                   Key = "RCMD"
	RIGHT_META                             Key = "RIGHT_META"
	RMETA                                  Key = "RMETA"
	K_PLAY_PAUSE                           Key = "K_PLAY_PAUSE"
	K_PP                                   Key = "K_PP"
	K_STOP2                                Key = "K_STOP2"
	K_PREVIOUS                             Key = "K_PREVIOUS"
	K_PREV                                 Key = "K_PREV"
	K_NEXT                                 Key = "K_NEXT"
	K_EJECT                                Key = "K_EJECT"
	K_VOLUME_UP2                           Key = "K_VOLUME_UP2"
	K_VOL_UP2                              Key = "K_VOL_UP2"
	K_VOLUME_DOWN2                         Key = "K_VOLUME_DOWN2"
	K_VOL_DN2                              Key = "K_VOL_DN2"
	K_MUTE2                                Key = "K_MUTE2"
	K_WWW                                  Key = "K_WWW"
	K_BACK                                 Key = "K_BACK"
	K_FORWARD                              Key = "K_FORWARD"
	K_STOP3                                Key = "K_STOP3"
	K_FIND2                                Key = "K_FIND2"
	K_SCROLL_UP                            Key = "K_SCROLL_UP"
	K_SCROLL_DOWN                          Key = "K_SCROLL_DOWN"
	K_EDIT                                 Key = "K_EDIT"
	K_SLEEP                                Key = "K_SLEEP"
	K_LOCK                                 Key = "K_LOCK"
	K_SCREENSAVER                          Key = "K_SCREENSAVER"
	K_COFFEE                               Key = "K_COFFEE"
	K_REFRESH                              Key = "K_REFRESH"
	K_CALCULATOR                           Key = "K_CALCULATOR"
	K_CALC                                 Key = "K_CALC"
	C_POWER                                Key = "C_POWER"
	C_PWR                                  Key = "C_PWR"
	C_RESET                                Key = "C_RESET"
	C_SLEEP                                Key = "C_SLEEP"
	C_SLEEP_MODE                           Key = "C_SLEEP_MODE"
	C_MENU                                 Key = "C_MENU"
	C_MENU_PICK                            Key = "C_MENU_PICK"
	C_MENU_SELECT                          Key = "C_MENU_SELECT"
	C_MENU_UP                              Key = "C_MENU_UP"
	C_MENU_DOWN                            Key = "C_MENU_DOWN"
	C_MENU_LEFT                            Key = "C_MENU_LEFT"
	C_MENU_RIGHT                           Key = "C_MENU_RIGHT"
	C_MENU_ESCAPE                          Key = "C_MENU_ESCAPE"
	C_MENU_ESC                             Key = "C_MENU_ESC"
	C_MENU_INCREASE                        Key = "C_MENU_INCREASE"
	C_MENU_INC                             Key = "C_MENU_INC"
	C_MENU_DECREASE                        Key = "C_MENU_DECREASE"
	C_MENU_DEC                             Key = "C_MENU_DEC"
	C_DATA_ON_SCREEN                       Key = "C_DATA_ON_SCREEN"
	C_CAPTIONS                             Key = "C_CAPTIONS"
	C_SUBTITLES                            Key = "C_SUBTITLES"
	C_SNAPSHOT                             Key = "C_SNAPSHOT"
	C_PIP                                  Key = "C_PIP"
	C_RED_BUTTON                           Key = "C_RED_BUTTON"
	C_RED                                  Key = "C_RED"
	C_GREEN_BUTTON                         Key = "C_GREEN_BUTTON"
	C_GREEN                                Key = "C_GREEN"
	C_BLUE_BUTTON                          Key = "C_BLUE_BUTTON"
	C_BLUE                                 Key = "C_BLUE"
	C_YELLOW_BUTTON                        Key = "C_YELLOW_BUTTON"
	C_YELLOW                               Key = "C_YELLOW"
	C_ASPECT                               Key = "C_ASPECT"
	C_BRIGHTNESS_INC                       Key = "C_BRIGHTNESS_INC"
	C_BRI_INC                              Key = "C_BRI_INC"
	C_BRI_UP                               Key = "C_BRI_UP"
	C_BRIGHTNESS_DEC                       Key = "C_BRIGHTNESS_DEC"
	C_BRI_DEC                              Key = "C_BRI_DEC"
	C_BRI_DN                               Key = "C_BRI_DN"
	C_BACKLIGHT_TOGGLE                     Key = "C_BACKLIGHT_TOGGLE"
	C_BKLT_TOG                             Key = "C_BKLT_TOG"
	C_BRIGHTNESS_MINIMUM                   Key = "C_BRIGHTNESS_MINIMUM"
	C_BRI_MIN                              Key = "C_BRI_MIN"
	C_BRIGHTNESS_MAXIMUM                   Key = "C_BRIGHTNESS_MAXIMUM"
	C_BRI_MAX                              Key = "C_BRI_MAX"
	C_BRIGHTNESS_AUTO                      Key = "C_BRIGHTNESS_AUTO"
	C_BRI_AUTO                             Key = "C_BRI_AUTO"
	C_MEDIA_STEP                           Key = "C_MEDIA_STEP"
	C_MODE_STEP                            Key = "C_MODE_STEP"
	C_RECALL_LAST                          Key = "C_RECALL_LAST"
	C_CHAN_LAST                            Key = "C_CHAN_LAST"
	C_MEDIA_COMPUTER                       Key = "C_MEDIA_COMPUTER"
	C_MEDIA_TV                             Key = "C_MEDIA_TV"
	C_MEDIA_WWW                            Key = "C_MEDIA_WWW"
	C_MEDIA_DVD                            Key = "C_MEDIA_DVD"
	C_MEDIA_PHONE                          Key = "C_MEDIA_PHONE"
	C_MEDIA_GUIDE                          Key = "C_MEDIA_GUIDE"
	C_MEDIA_VIDEOPHONE                     Key = "C_MEDIA_VIDEOPHONE"
	C_MEDIA_GAMES                          Key = "C_MEDIA_GAMES"
	C_MEDIA_MESSAGES                       Key = "C_MEDIA_MESSAGES"
	C_MEDIA_CD                             Key = "C_MEDIA_CD"
	C_MEDIA_VCR                            Key = "C_MEDIA_VCR"
	C_MEDIA_TUNER                          Key = "C_MEDIA_TUNER"
	C_QUIT                                 Key = "C_QUIT"
	C_HELP                                 Key = "C_HELP"
	C_MEDIA_TAPE                           Key = "C_MEDIA_TAPE"
	C_MEDIA_CABLE                          Key = "C_MEDIA_CABLE"
	C_MEDIA_SATELLITE                      Key = "C_MEDIA_SATELLITE"
	C_MEDIA_HOME                           Key = "C_MEDIA_HOME"
	C_CHANNEL_INC                          Key = "C_CHANNEL_INC"
	C_CHAN_INC                             Key = "C_CHAN_INC"
	C_CHANNEL_DEC                          Key = "C_CHANNEL_DEC"
	C_CHAN_DEC                             Key = "C_CHAN_DEC"
	C_MEDIA_VCR_PLUS                       Key = "C_MEDIA_VCR_PLUS"
	C_PLAY                                 Key = "C_PLAY"
	C_PAUSE                                Key = "C_PAUSE"
	C_RECORD                               Key = "C_RECORD"
	C_REC                                  Key = "C_REC"
	C_FAST_FORWARD                         Key = "C_FAST_FORWARD"
	C_FF                                   Key = "C_FF"
	C_REWIND                               Key = "C_REWIND"
	C_RW                                   Key = "C_RW"
	C_NEXT                                 Key = "C_NEXT"
	C_PREVIOUS                             Key = "C_PREVIOUS"
	C_PREV                                 Key = "C_PREV"
	C_STOP                                 Key = "C_STOP"
	C_EJECT                                Key = "C_EJECT"
	C_RANDOM_PLAY                          Key = "C_RANDOM_PLAY"
	C_SHUFFLE                              Key = "C_SHUFFLE"
	C_REPEAT                               Key = "C_REPEAT"
	C_SLOW_TRACKING                        Key = "C_SLOW_TRACKING"
	C_SLOW2                                Key = "C_SLOW2"
	C_STOP_EJECT                           Key = "C_STOP_EJECT"
	C_PLAY_PAUSE                           Key = "C_PLAY_PAUSE"
	C_PP                                   Key = "C_PP"
	C_VOICE_COMMAND                        Key = "C_VOICE_COMMAND"
	C_MUTE                                 Key = "C_MUTE"
	C_BASS_BOOST                           Key = "C_BASS_BOOST"
	C_VOLUME_UP                            Key = "C_VOLUME_UP"
	C_VOL_UP                               Key = "C_VOL_UP"
	C_VOLUME_DOWN                          Key = "C_VOLUME_DOWN"
	C_VOL_DN                               Key = "C_VOL_DN"
	C_SLOW                                 Key = "C_SLOW"
	C_ALTERNATE_AUDIO_INCREMENT            Key = "C_ALTERNATE_AUDIO_INCREMENT"
	C_ALT_AUDIO_INC                        Key = "C_ALT_AUDIO_INC"
	C_AL_CCC                               Key = "C_AL_CCC"
	C_AL_WORD                              Key = "C_AL_WORD"
	C_AL_TEXT_EDITOR                       Key = "C_AL_TEXT_EDITOR"
	C_AL_SPREADSHEET                       Key = "C_AL_SPREADSHEET"
	C_AL_SHEET                             Key = "C_AL_SHEET"
	C_AL_GRAPHICS_EDITOR                   Key = "C_AL_GRAPHICS_EDITOR"
	C_AL_PRESENTATION                      Key = "C_AL_PRESENTATION"
	C_AL_DATABASE                          Key = "C_AL_DATABASE"
	C_AL_DB                                Key = "C_AL_DB"
	C_AL_EMAIL                             Key = "C_AL_EMAIL"
	C_AL_MAIL                              Key = "C_AL_MAIL"
	C_AL_NEWS                              Key = "C_AL_NEWS"
	C_AL_VOICEMAIL                         Key = "C_AL_VOICEMAIL"
	C_AL_CONTACTS                          Key = "C_AL_CONTACTS"
	C_AL_ADDRESS_BOOK                      Key = "C_AL_ADDRESS_BOOK"
	C_AL_CALENDAR                          Key = "C_AL_CALENDAR"
	C_AL_CAL                               Key = "C_AL_CAL"
	C_AL_TASK_MANAGER                      Key = "C_AL_TASK_MANAGER"
	C_AL_JOURNAL                           Key = "C_AL_JOURNAL"
	C_AL_FINANCE                           Key = "C_AL_FINANCE"
	C_AL_CALCULATOR                        Key = "C_AL_CALCULATOR"
	C_AL_CALC                              Key = "C_AL_CALC"
	C_AL_AV_CAPTURE_PLAYBACK               Key = "C_AL_AV_CAPTURE_PLAYBACK"
	C_AL_MY_COMPUTER                       Key = "C_AL_MY_COMPUTER"
	C_AL_WWW                               Key = "C_AL_WWW"
	C_AL_NETWORK_CHAT                      Key = "C_AL_NETWORK_CHAT"
	C_AL_CHAT                              Key = "C_AL_CHAT"
	C_AL_LOGOFF                            Key = "C_AL_LOGOFF"
	C_AL_LOCK                              Key = "C_AL_LOCK"
	C_AL_SCREENSAVER                       Key = "C_AL_SCREENSAVER"
	C_AL_COFFEE                            Key = "C_AL_COFFEE"
	C_AL_CONTROL_PANEL                     Key = "C_AL_CONTROL_PANEL"
	C_AL_SELECT_TASK                       Key = "C_AL_SELECT_TASK"
	C_AL_NEXT_TASK                         Key = "C_AL_NEXT_TASK"
	C_AL_PREVIOUS_TASK                     Key = "C_AL_PREVIOUS_TASK"
	C_AL_PREV_TASK                         Key = "C_AL_PREV_TASK"
	C_AL_HELP                              Key = "C_AL_HELP"
	C_AL_DOCUMENTS                         Key = "C_AL_DOCUMENTS"
	C_AL_DOCS                              Key = "C_AL_DOCS"
	C_AL_SPELLCHECK                        Key = "C_AL_SPELLCHECK"
	C_AL_SPELL                             Key = "C_AL_SPELL"
	C_AL_KEYBOARD_LAYOUT                   Key = "C_AL_KEYBOARD_LAYOUT"
	C_AL_SCREEN_SAVER                      Key = "C_AL_SCREEN_SAVER"
	C_AL_FILE_BROWSER                      Key = "C_AL_FILE_BROWSER"
	C_AL_FILES                             Key = "C_AL_FILES"
	C_AL_IMAGE_BROWSER                     Key = "C_AL_IMAGE_BROWSER"
	C_AL_IMAGES                            Key = "C_AL_IMAGES"
	C_AL_AUDIO_BROWSER                     Key = "C_AL_AUDIO_BROWSER"
	C_AL_AUDIO                             Key = "C_AL_AUDIO"
	C_AL_MUSIC                             Key = "C_AL_MUSIC"
	C_AL_MOVIE_BROWSER                     Key = "C_AL_MOVIE_BROWSER"
	C_AL_MOVIES                            Key = "C_AL_MOVIES"
	C_AL_INSTANT_MESSAGING                 Key = "C_AL_INSTANT_MESSAGING"
	C_AL_IM                                Key = "C_AL_IM"
	C_AL_OEM_FEATURES                      Key = "C_AL_OEM_FEATURES"
	C_AL_TIPS                              Key = "C_AL_TIPS"
	C_AL_TUTORIAL                          Key = "C_AL_TUTORIAL"
	C_AC_NEW                               Key = "C_AC_NEW"
	C_AC_OPEN                              Key = "C_AC_OPEN"
	C_AC_CLOSE                             Key = "C_AC_CLOSE"
	C_AC_EXIT                              Key = "C_AC_EXIT"
	C_AC_SAVE                              Key = "C_AC_SAVE"
	C_AC_PRINT                             Key = "C_AC_PRINT"
	C_AC_PROPERTIES                        Key = "C_AC_PROPERTIES"
	C_AC_PROPS                             Key = "C_AC_PROPS"
	C_AC_UNDO                              Key = "C_AC_UNDO"
	C_AC_COPY                              Key = "C_AC_COPY"
	C_AC_CUT                               Key = "C_AC_CUT"
	C_AC_PASTE                             Key = "C_AC_PASTE"
	C_AC_FIND                              Key = "C_AC_FIND"
	C_AC_SEARCH                            Key = "C_AC_SEARCH"
	C_AC_GOTO                              Key = "C_AC_GOTO"
	C_AC_HOME                              Key = "C_AC_HOME"
	C_AC_BACK                              Key = "C_AC_BACK"
	C_AC_FORWARD                           Key = "C_AC_FORWARD"
	C_AC_STOP                              Key = "C_AC_STOP"
	C_AC_REFRESH                           Key = "C_AC_REFRESH"
	C_AC_BOOKMARKS                         Key = "C_AC_BOOKMARKS"
	C_AC_FAVORITES                         Key = "C_AC_FAVORITES"
	C_AC_FAVOURITES                        Key = "C_AC_FAVOURITES"
	C_AC_ZOOM_IN                           Key = "C_AC_ZOOM_IN"
	C_AC_ZOOM_OUT                          Key = "C_AC_ZOOM_OUT"
	C_AC_ZOOM                              Key = "C_AC_ZOOM"
	C_AC_VIEW_TOGGLE                       Key = "C_AC_VIEW_TOGGLE"
	C_AC_SCROLL_UP                         Key = "C_AC_SCROLL_UP"
	C_AC_SCROLL_DOWN                       Key = "C_AC_SCROLL_DOWN"
	C_AC_EDIT                              Key = "C_AC_EDIT"
	C_AC_CANCEL                            Key = "C_AC_CANCEL"
	C_AC_INSERT                            Key = "C_AC_INSERT"
	C_AC_INS                               Key = "C_AC_INS"
	C_AC_DEL                               Key = "C_AC_DEL"
	C_AC_REDO                              Key = "C_AC_REDO"
	C_AC_REPLY                             Key = "C_AC_REPLY"
	C_AC_FORWARD_MAIL                      Key = "C_AC_FORWARD_MAIL"
	C_AC_SEND                              Key = "C_AC_SEND"
	C_AC_DESKTOP_SHOW_ALL_WINDOWS          Key = "C_AC_DESKTOP_SHOW_ALL_WINDOWS"
	C_AC_DESKTOP_SHOW_ALL_APPLICATIONS     Key = "C_AC_DESKTOP_SHOW_ALL_APPLICATIONS"
	C_KEYBOARD_INPUT_ASSIST_PREVIOUS       Key = "C_KEYBOARD_INPUT_ASSIST_PREVIOUS"
	C_KBIA_PREV                            Key = "C_KBIA_PREV"
	C_KEYBOARD_INPUT_ASSIST_NEXT           Key = "C_KEYBOARD_INPUT_ASSIST_NEXT"
	C_KBIA_NEXT                            Key = "C_KBIA_NEXT"
	C_KEYBOARD_INPUT_ASSIST_PREVIOUS_GROUP Key = "C_KEYBOARD_INPUT_ASSIST_PREVIOUS_GROUP"
	C_KBIA_PREV_GRP                        Key = "C_KBIA_PREV_GRP"
	C_KEYBOARD_INPUT_ASSIST_NEXT_GROUP     Key = "C_KEYBOARD_INPUT_ASSIST_NEXT_GROUP"
	C_KBIA_NEXT_GRP                        Key = "C_KBIA_NEXT_GRP"
	C_KEYBOARD_INPUT_ASSIST_ACCEPT         Key = "C_KEYBOARD_INPUT_ASSIST_ACCEPT"
	C_KBIA_ACCEPT                          Key = "C_KBIA_ACCEPT"
	C_KEYBOARD_INPUT_ASSIST_CANCEL         Key = "C_KEYBOARD_INPUT_ASSIST_CANCEL"
	C_KBIA_CANCEL                          Key = "C_KBIA_CANCEL"
	C_AC_NEXT_KEYBOARD_LAYOUT_SELECT       Key = "C_AC_NEXT_KEYBOARD_LAYOUT_SELECT"
	GLOBE                                  Key = "GLOBE"
)
